version: '3.8'
services:
  db:
    image: cyprientemateu/sixfure-db:DB_IMAGE_TAG
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: WEATHER_APP_MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: sixfure
      MYSQL_USER: sixfure
      MYSQL_PASSWORD: WEATHER_APP_MYSQL_PASSWORD
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - sixfure
    restart: always
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  redis:
    image: cyprientemateu/sixfure-redis:REDIS_IMAGE_TAG
    ports:
      - "6379:6379"
    environment:
      REDIS_USER: WEATHER_APP_REDIS_PASSWORD_USERNAME
      REDIS_PASSWORD: WEATHER_APP_REDIS_PASSWORD
    volumes:
      - redis-data:/data
    networks:
      - sixfure
    restart: always
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  ui:
    image: cyprientemateu/sixfure-ui:UI_IMAGE_TAG
    ports:
      - "3000:3000"
    environment:
      AUTH_HOST: auth
      AUTH_PORT: 8080
      WEATHER_HOST: weather
      WEATHER_PORT: 5000
      REDIS_USER: redis
      REDIS_PASSWORD: redis
    networks:
      - sixfure
    restart: always
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  weather:
    image: cyprientemateu/sixfure-weather:WEATHER_IMAGE_TAG
    ports:
      - "5000:5000"
    environment:
      APIKEY: WEATHER_API-TOKEN
    networks:
      - sixfure
    restart: always
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  auth:
    image: cyprientemateu/sixfure-auth:AUTH_IMAGE_TAG
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PASSWORD: WEATHER_APP_MYSQL_ROOT_PASSWORD
    networks:
      - sixfure
    restart: always
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  sixfure:
    driver: overlay

volumes:
  db-data:
  redis-data:
